import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }
decorations = "Buttonless"
# opacity = 0.8
opacity = 1 

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
size = 16
