#!/usr/bin/env sh

# Global Settings
yabai -m config    window_placement             second_child  
yabai -m config    window_zoom_persist          on            
yabai -m config    insert_feedback_color        0xffd75f5f    
yabai -m config    split_ratio                  0.50          
yabai -m config    split_type                   auto          
yabai -m config    auto_balance                 off           

# mouse settings
yabai -m config    mouse_modifier               fn            
yabai -m config    mouse_action1                move          
yabai -m config    mouse_action2                resize        
yabai -m config    mouse_drop_action            swap
yabai -m config    mouse_follows_focus          off           
yabai -m config    focus_follows_mouse          off           
yabai -m config    window_origin_display        default       

# Space Settings
yabai -m config    layout                       bsp           
yabai -m config    top_padding                  10            
yabai -m config    bottom_padding               10            
yabai -m config    left_padding                 10            
yabai -m config    right_padding                10            
yabai -m config    window_gap                   10            

# Signal to focus moved window
# focus window after active space changes
yabai -m signal --add event=space_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# focus window after active display changes
yabai -m signal --add event=display_changed action="yabai -m window --focus \$(yabai -m query --windows --space | jq .[0].id)"

# disable specific apps
yabai -m rule --add app="^System Settings" manage=off
yabai -m rule --add app="^Calculator" manage=off
yabai -m rule --add app="^Alfred" manage=off
